name: publish to test-drafts website repo

on:
  workflow_dispatch:
    branches:
      - main  # User can select branch to deploy when running the action

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.145.0'
          # extended: true

      - name: Build
        run: hugo --buildDrafts --minify --baseURL "https://roman-gardens.github.io/test-drafts/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY_TEST_DRAFTS }}
          external_repository: roman-gardens/test-drafts
          publish_branch: main
          publish_dir: ./docs
          commit_message: ${{ github.event.head_commit.message }}
